name-template: 'v$RESOLVED_VERSION 🎉'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'enhancement'
      - 'test'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'test'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'test'
  - title: '🛠️ Refactors'
    labels:
      - 'refactor'
      - 'test'
  - title: '🔄 Reverts'
    labels:
      - 'revert'
      - 'test'
  - title: '📝 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '🏁 Testing'
    labels:
      - 'test'
  - title: '💄 Style'
    labels:
      - 'style'
  - title: '🏗️ Build'
    labels:
      - 'build'
  - title: '🔧 CI/CD'
    labels:
      - 'ci'
      - 'cd'

autolabeler:
  - label: 'build'
    title:
      - '/build/i'
  - label: 'chore'
    title:
      - '/chore/i'
  - label: 'ci'
    title:
      - '/ci/i'
  - label: 'docs'
    title:
      - '/docs/i'
  - label: 'feat'
    title:
      - '/feat/i'
  - label: 'fix'
    title:
      - '/fix/i'
  - label: 'perf'
    title:
      - '/perf/i'
  - label: 'refactor'
    title:
      - '/refactor/i'
  - label: 'revert'
    title:
      - '/revert/i'
  - label: 'style'
    title:
      - '/style/i'
  - label: 'test'
    title:
      - '/test/i'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES