name: Create release

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: Update release draft
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: release-drafter/release-drafter@v5
        id: create_release
        with:
          commitish: main # according to this issue: https://github.com/release-drafter/release-drafter/issues/1125#issuecomment-1471142225
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  execute_tests_build:
    uses: ./.github/workflows/test-build.yaml
    name: Execute tests and build

  upload_binary:
    runs-on: ubuntu-latest
    needs:
      - update_release_draft
      - execute_tests_build
    name: Upload binary to release draft
    steps:
      - name: Download Compiled Binary Artifact
        uses: actions/download-artifact@v2
        with:
          name: glados-exe

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.update_release_draft.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./glados-exe
          asset_name: glados
          asset_content_type: application/octet-stream
